using System.Diagnostics;

namespace AppleIIDiskReader.Tests;

public class AppleIIDiskTests
{
    public static TheoryData<string> DiskImages => new()
    {
        "appleIIDos.dsk",
        "appleIIDosSide2.dsk",
        "bankSt3-10Side2.dsk",
        "bankSt3-5Side2.dsk",
        "bankSt3-8Side2.dsk",
        "bankStreetWriter.dsk",
        "bankStreetWriterMiscFiles.dsk",
        "bankStreetWriterMiscFilesSide2.dsk",
        "bankStreetWriterSide2.dsk",
        "bestElectronicWordBookEverSide2.dsk",
        "britannicaDragonsKeep.dsk",
        "britannicaDragonsKeepSide2.dsk",
        "britannicaGelfingAdventure.dsk",
        "britannicaGelfingAdventureSide2.dsk",
        "childrensWritingCenterC.dsk",
        "childrensWritingCenterCSide2.dsk",
        "childrensWritingPictureDisk.dsk",
        "climatesOfTheWorld.dsk",
        "climatesOfTheWorldSide2.dsk",
        "compaqMsDos3.31b.dsk",
        "compaqMsDos3.31bDisc2.dsk",
        "compaqMsDos3.31bDisc2Side2.dsk",
        "compaqMsDos3.31bSide2.dsk",
        "compaqMsDosStartup.dsk",
        "compaqMsDosStartupSide2.dsk",
        "compaqUserDiagnostics.dsk",
        "compaqUserDiagnosticsSide2.dsk",
        "compaqUserPrograms.dsk",
        "compaqUserProgramsSide2.dsk",
        "computerClubLogoPrograms.dsk",
        "computerClubLogoProgramsSide2.dsk",
        "computerLearningFun.dsk",
        "computerLearningFunSide2.dsk",
        "copyIIPlus4.4c.dsk",
        "copyIIPlus4.4cSide2.dsk",
        "copyIIPlus5.5.dsk",
        "copyIIPlus5.5Side2.dsk",
        "copyIIPlusPregnySide2.dsk",
        "copyIIPlusSide2.dsk",
        "cp-m2.2.dsk",
        "cp-m2.2Side2.dsk",
        "cp-m2.2WorkingDiskSide2.dsk",
        "cp-m2.2workingDisk.dsk",
        "cpcInstall1.dsk",
        "cpcInstall1side2.dsk",
        "cpcInstall2.dsk",
        "cpcInstall2side2.dsk",
        "denizAurelieCindyAlexiaAklizaSide2.dsk",
        "dlmDragonMix.dsk",
        "dlmDragonMixSide2.dsk",
        "dlmMeteorMultiplication.dsk",
        "dlmMeteorMultiplicationSide2.dsk",
        "engineeringPlasticsPart2.dsk",
        "engineeringPlasticsPart2Side2.dsk",
        "etherlink.dsk",
        "etherlinkSide2.dsk",
        "fddimon2.05disk1.dsk",
        "fddimon2.05disk1Side2.dsk",
        "fddimon2.05disk1copy.dsk",
        "fddimon2.05disk1copy2.dsk",
        "fddimon2.05disk1copy2Side2.dsk",
        "fddimon2.05disk1copy3.dsk",
        "fddimon2.05disk1copy3Side2.dsk",
        "fddimon2.05disk1copy4.dsk",
        "fddimon2.05disk1copy4Side2.dsk",
        "fddimon2.05disk1copy5.dsk",
        "fddimon2.05disk1copy5Side2.dsk",
        "fddimon2.05disk1copySide2.dsk",
        "fddimon2.05disk2.dsk",
        "fddimon2.05disk2Side2.dsk",
        "fddimon2.05disk2copy.dsk",
        "fddimon2.05disk2copy2.dsk",
        "fddimon2.05disk2copy2Side2.dsk",
        "fddimon2.05disk2copy3.dsk",
        "fddimon2.05disk2copy3Side2.dsk",
        "fddimon2.05disk2copy4.dsk",
        "fddimon2.05disk2copy4Side2.dsk",
        "fddimon2.05disk2copy5.dsk",
        "fddimon2.05disk2copy5Side2.dsk",
        "fddimon2.05disk2copySide2.dsk",
        "fileCopyUtilities.dsk",
        "fileCopyUtilitiesSide2.dsk",
        "group3Side2.dsk",
        "hayesSmartcomII.dsk",
        "hayesSmartcomIISide2.dsk",
        "hitchhikersGuideSide2.dsk",
        "inSearchOfTheMostAmazingThing.dsk",
        "inSearchOfTheMostAmazingThingSide2.dsk",
        "joelAndAliCopy.dsk",
        "joelAndAliCopySide2.dsk",
        "junglesRainbowInstantZoo.dsk",
        "junglesRainbowInstantZooSide2.dsk",
        "kermitUUEncodeUUDecode.dsk",
        "kermitUUEncodeUUDecodeSide2.dsk",
        "lAppleAuTravailSide2.dsk",
        "lastDisc10Jul91.dsk",
        "lastDisc10Jul91Side2.dsk",
        "lastDiscAug92.dsk",
        "lastDiskAug92Side2.dsk",
        "logoRobot.dsk",
        "logoRobotSide2.dsk",
        "logowriter1stSide2.dsk",
        "logowriter1thSide2.dsk",
        "logowriterAngelaSeiriolCatherineJacquelineRahulMoii6thSide2.dsk",
        "logowriterCraigMatthewRaghanMirandaLinneaJustin6thSide2.dsk",
        "logowriterGroup1Side2.dsk",
        "logowriterGroup2Side2.dsk",
        "logowriterGroup3Side2.dsk",
        "logowriterGroup3copySide2.dsk",
        "logowriterGroup4Side2.dsk",
        "logowriterHillTarjuroRintaroAlexisAgnelaBrigitSide2.dsk",
        "logowriterNicoleSide2.dsk",
        "logowriterRonaldJudyKellyJessieLauraKevinGiugi3rdSide2.dsk",
        "lotua123SystemDiskSide2.dsk",
        "lotus123PrintgraphDisk.dsk",
        "lotus123PrintgraphDiskSide2.dsk",
        "lotus123SystemDisk.dsk",
        "lotus123SystemDisk2.dsk",
        "lotus123SystemDisk2Side2.dsk",
        "lotus123TutorialDisk.dsk",
        "lotus123TutorialDisk2.dsk",
        "lotus123TutorialDisk2Side2.dsk",
        "lotus123TutorialDiskSide2.dsk",
        "lotus123UtilityDisk.dsk",
        "lotus123UtilityDiskSide2.dsk",
        "masm.dsk",
        "masmSide2.dsk",
        "mathMan.dsk",
        "mathManSide2.dsk",
        "meccAdditionLogician.dsk",
        "meccAdditionLogicianSide2.dsk",
        "meccAdventuresWithFractions.dsk",
        "meccCircusMath.dsk",
        "meccCircusMathSide2.dsk",
        "meccClockworks.dsk",
        "meccClockworksSide2.dsk",
        "meccEarlyAddition.dsk",
        "meccEarlyAddition1.2.dsk",
        "meccEarlyAddition1.2Side2.dsk",
        "meccGraph.dsk",
        "meccGraphSide2.dsk",
        "meccMultiplicationPuzzles.dsk",
        "meccMultiplicationPuzzlesSide2.dsk",
        "meccNumberMuncher.dsk",
        "meccNumberMuncherSide2.dsk",
        "microsoftBasic80.dsk",
        "microsoftBasic80Side2.dsk",
        "microzine11LetterFromTheEditorTheDarkTowerComputerStuff.dsk",
        "microzine11SecretCoderStickerFactoryBackPageWhatsNext.dsk",
        "microzine16LetterFromTheEditorTicketsToAmericaComputerStuff.dsk",
        "microzine16ShiftyShapesSolarPilotATravellersGuideToFantasticPlacesWhatsNext.dsk",
        "microzine17LetterFromTheEditorMicroAgentOfTheBodyGuardComputerStuff.dsk",
        "microzine17MissionMixUpMarvelousMenageriesBASICTraining.dsk",
        "microzine1983RideTheWindWordLadderWhatsNext.dsk",
        "microzine1983WhatsInsideNorthwoodsAdventureMelodyMakerComputerStuff.dsk",
        "microzine1985LetterFromTheEditorTheShotHeardRoundTheWorldComputerStuff.dsk",
        "microzine1985SailingBillboardBackPageWhatsNext.dsk",
        "microzine20InteractionsHerosAndVillainsMonitorMystery.dsk",
        "microzine20LettersVoyageToSeeWhatsOnTheBottomComputerStuff.dsk",
        "microzine21FabulousKidsFilInTheBlanksMonitorMystery.dsk",
        "microzine21LettersRobotRescueComputerStuff.dsk",
        "microzine22LettersTheHauntedChannelsComputerStuff.dsk",
        "microzine22MathMallMonitorMystery.dsk",
        "microzine22Newsprint.dsk",
        "microzine22NewsprintSide2.dsk",
        "microzine23LettersEscapeFromANTcatrazComputerStuff.dsk",
        "microzine23MathMallMonitorMystery.dsk",
        "microzine23desktopPublishing.dsk",
        "microzine23desktopPublishingSide2.dsk",
        "microzine24BannerMaker.dsk",
        "microzine24BannerMakerSide2.dsk",
        "microzineDataA.MelodySide2.dsk",
        "mikeJorickJovanChrisNikhilSide2.dsk",
        "msDos5.0no2.dsk",
        "msDos5.0no2Side2.dsk",
        "msKermitForPregny.dsk",
        "msKermitForPregnySide2.dsk",
        "mysteryHouse.dsk",
        "mysteryHouseMusicofErin.dsk",
        "mysteryHouseMusicofErinSide2.dsk",
        "mysteryHouseSide2.dsk",
        "nadiaJasmineAlexFrancescaAhoneSide2.dsk",
        "newPrintShopData1A1B.dsk",
        "nikolasMuratPaulAzeemChristinaSide2.dsk",
        "no10.dsk",
        "no10Side2.dsk",
        "no11.dsk",
        "no11Side2.dsk",
        "no13.dsk",
        "no13Side2.dsk",
        "no14.dsk",
        "no14Side2.dsk",
        "no18.dsk",
        "no18Side2.dsk",
        "no6.dsk",
        "no6Side2.dsk",
        "no7.dsk",
        "no7Side2.dsk",
        "no8.dsk",
        "no8Side2.dsk",
        "no9.dsk",
        "no9Side2.dsk",
        "perfectCalcLessonsDisk.dsk",
        "perfectCalcLessonsDiskSide2.dsk",
        "perfectFilerFilerDisk.dsk",
        "perfectFilerFilerSide2.dsk",
        "perfectFilerWorkingDisk.dsk",
        "perfectFilerWorkingDiskSide2.dsk",
        "perfectSpeller.dsk",
        "perfectSpellerSide2.dsk",
        "perfectWriter.dsk",
        "perfectWriterEditDisk.dsk",
        "perfectWriterEditDisk2.dsk",
        "perfectWriterEditDisk2Side2.dsk",
        "perfectWriterEditDiskSide2.dsk",
        "perfectWriterLessonsDisk.dsk",
        "perfectWriterLessonsDisk2.dsk",
        "perfectWriterLessonsDisk2Side2.dsk",
        "perfectWriterLessonsDiskSide2.dsk",
        "perfectWriterSide2.dsk",
        "perfectWriterWorkingDisk.dsk",
        "perfectWriterWorkingDiskSide2.dsk",
        "printShop3,4Side2.dsk",
        "printShopChristmas.dsk",
        "printShopChristmasDisk1.dsk",
        "printShopChristmasDisk1Side2.dsk",
        "printShopChristmasDisk2.dsk",
        "printShopChristmasDisk2Side2.dsk",
        "printShopCompanionSideA.dsk",
        "printShopCompanionSideASide2.dsk",
        "printShopCompanionSideB.dsk",
        "printShopCompanionSideBSide2.dsk",
        "printShopCopySide2.dsk",
        "printShopEpsonSide2.dsk",
        "printShopGraphicsLibrary.dsk",
        "printShopGraphicsLibrarySide2.dsk",
        "printShopLib1,2.dsk",
        "printShopLib1,2Side2.dsk",
        "printShopLib3,4.dsk",
        "printShopLib5,6.dsk",
        "printShopLib5,6Side2.dsk",
        "printShopProgramDiskImageWriterSide2.dsk",
        "profitPlan.dsk",
        "profitPlanSide2.dsk",
        "profitPlanWorkingDisk.dsk",
        "profitPlanWorkingDiskSide2.dsk",
        "rockysBoots.dsk",
        "rockysBootsSide2.dsk",
        "shiftySam.dsk",
        "shiftySamSide2.dsk",
        "skcBlank1.dsk",
        "skcBlank10.dsk",
        "skcBlank10Side2.dsk",
        "skcBlank11.dsk",
        "skcBlank11Side2.dsk",
        "skcBlank12.dsk",
        "skcBlank12Side2.dsk",
        "skcBlank13.dsk",
        "skcBlank13Side2.dsk",
        "skcBlank14.dsk",
        "skcBlank14Side2.dsk",
        "skcBlank15.dsk",
        "skcBlank15Side2.dsk",
        "skcBlank16.dsk",
        "skcBlank16Side2.dsk",
        "skcBlank17.dsk",
        "skcBlank17Side2.dsk",
        "skcBlank1Side2.dsk",
        "skcBlank2.dsk",
        "skcBlank2Side2.dsk",
        "skcBlank3.dsk",
        "skcBlank3Side2.dsk",
        "skcBlank4.dsk",
        "skcBlank4Side2.dsk",
        "skcBlank5.dsk",
        "skcBlank5Side2.dsk",
        "skcBlank6.dsk",
        "skcBlank6Side2.dsk",
        "skcBlank7.dsk",
        "skcBlank7Side2.dsk",
        "skcBlank8.dsk",
        "skcBlank8Side2.dsk",
        "skcBlank9.dsk",
        "skcBlank9Side2.dsk",
        "spellicopterSide2.dsk",
        "suiteUtil.dsk",
        "suiteUtilSide2.dsk",
        "superPrint121aDisk1.dsk",
        "superPrint121aDisk1Side2.dsk",
        "superPrint121cDisk1.dsk",
        "superPrint121cDisk1Side2.dsk",
        "superPrintDisk1.dsk",
        "superPrintDisk2Side2.dsk",
        "superPrintDisk3Side2.dsk",
        "surveyTaker.dsk",
        "surveyTakerBlank.dsk",
        "surveyTakerBlankSide2.dsk",
        "surveyTakerSide2.dsk",
        "synerneticsFddiSmt.dsk",
        "synerneticsFddiSmtSide2.dsk",
        "synerneticsSmtDemo.dsk",
        "synerneticsSmtDemoSide2.dsk",
        "takingResponsibility.dsk",
        "tdkBlank.dsk",
        "tdkBlankSide2.dsk",
        "teachMeWordPerfect5.1Disc1.dsk",
        "teachMeWordPerfect5.1Disc1Side2.dsk",
        "teachMeWordPerfect5.1Disc2.dsk",
        "teachMeWordPerfect5.1Disc2Side2.dsk",
        "theBankStreetWriter.dsk",
        "theBankStreetWriterCopy.dsk",
        "theBankStreetWriterCopy2.dsk",
        "theBankStreetWriterCopy2Side2.dsk",
        "theBankStreetWriterCopySide2.dsk",
        "theBankStreetWriterSide2.dsk",
        "theChildrensWritingPublishingCenter113c.dsk",
        "theKingsRule.dsk",
        "theKingsRuleSide2.dsk",
        "theWonderfulWorldOfPawsStartupDisk.dsk",
        "theWonderfulWorldOfPawsStartupDiskSide2.dsk",
        "theWordPlus.dsk",
        "theWordPlusSide2.dsk",
        "theWordWorkingDisk.dsk",
        "theWordWorkingDiskSide2.dsk",
        "travelingThroughTheSolarSystem.dsk",
        "travelingThroughTheSolarSystemSide2.dsk",
        "trollsTale.dsk",
        "trollsTaleSide2.dsk",
        "typeToLearnBenDisk1.dsk",
        "typeToLearnBenDisk1Side2.dsk",
        "typeToLearnBenDisk2.dsk",
        "typeToLearnBenDisk2Side2.dsk",
        "typeToLearnDisk1.dsk",
        "typeToLearnDisk1Side2.dsk",
        "typeToLearnDisk2.dsk",
        "typeToLearnDisk2Side2.dsk",
        "utilitairesSystemPourLeIIc.dsk",
        "utilitairesSystemPourLeIIcSide2.dsk",
        "wallysWordWorks.dsk",
        "wallysWordWorksSide2.dsk",
        "whereInTheWorldIsCarmenSandiego.dsk",
        "winnieThePooh.dsk",
        "winnieThePoohSide2.dsk",
        "winnieThePoohStartup.dsk",
        "winnieThePoohStartupSide2.dsk",
        "wordstar.dsk",
        "wordstarSide2.dsk",
        "writingAndPublishingStorage.dsk",
        "writingAndPublishingStorageSide2.dsk",
    };

    [Theory]
    [MemberData(nameof(DiskImages))]
    public void Ctor_Stream(string diskName)
    {
        var filePath = Path.Combine("Samples", diskName);
        using var stream = File.OpenRead(filePath);
        var image = new AppleIIDisk(stream);

        // Create output directory based on disk name (without extension)
        string diskNameWithoutExtension = Path.GetFileNameWithoutExtension(diskName);
        string outputDir = Path.Combine("Output", diskNameWithoutExtension);
        Directory.CreateDirectory(outputDir);

        foreach (var fileEntry in image.EnumerateFileEntries())
        {
            Debug.WriteLine($"File: {fileEntry.FileName}, Type: {fileEntry.FileType}, Locked: {fileEntry.IsLocked}, Length: {fileEntry.LengthInSectors} sectors");

            if (fileEntry.IsDeleted)
            {
                Debug.WriteLine("  Skipping deleted file.");
                continue;
            }

            // Create a safe filename (replace invalid characters)
            string safeFileName = string.Join("_", fileEntry.FileName.Split(Path.GetInvalidFileNameChars()));

            // Add extension based on file type
            string extension = fileEntry.FileType switch
            {
                AppleIIFileType.Text => ".txt",
                AppleIIFileType.IntegerBasic => ".int",
                AppleIIFileType.ApplesoftBasic => ".bas",
                AppleIIFileType.Binary => ".bin",
                AppleIIFileType.Relocatable => ".rel",
                _ => ".dat"
            };

            string outputPath = Path.Combine(outputDir, safeFileName + extension);

            // For text files, convert from Apple II high ASCII to standard ASCII
            if (fileEntry.FileType == AppleIIFileType.Text)
            {
                string text = image.ReadTextFile(fileEntry);
                File.WriteAllText(outputPath, text);
                Debug.WriteLine($"  Wrote text file ({text.Length} chars) to {outputPath}");
            }
            else
            {
                byte[] data = image.ReadFileData(fileEntry);
                File.WriteAllBytes(outputPath, data);
                Debug.WriteLine($"  Wrote {data.Length} bytes to {outputPath}");
            }
        }
    }

    [Fact]
    public void Ctor_NullStream_ThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>("stream", () => new AppleIIDisk(null!));
    }
}
